import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/providers/theme-provider";
import Navbar from "@/components/navbar";
import localFont from "next/font/local";
import Footer from "@/components/footer";
import NextUIProviders from "@/providers/next-ui-provider";

const font = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "LENS Corporation | Biometric & Computer Vision",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <NextUIProviders>
            <Navbar />
            {children}
            <Footer />
          </NextUIProviders>
        </ThemeProvider>
      </body>
    </html>
  );
}
